apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app: nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs
          image: your-docker-username/your-nodejs-image-name:latest
          ports:
            - containerPort: 3000
          env:
            - name: node_env
              value: production

apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP

